#!/usr/bin/env python3
"""Build memory graph from watercooler threads.

Usage:
    ./scripts/build_memory_graph.py /path/to/threads-repo
    ./scripts/build_memory_graph.py /path/to/threads-repo --export-leanrag ./output
    ./scripts/build_memory_graph.py /path/to/threads-repo -o graph.json --export-leanrag ./output

For LLM features (embeddings, entity extraction, summarization):
    1. Export to LeanRAG format with --export-leanrag
    2. Run LeanRAG pipeline on the exported data
    See: ../LeanRAG/SETUP.md for the full LeanRAG pipeline
"""

import argparse
import sys
from pathlib import Path

# Add src to path for local dev
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from watercooler_memory import MemoryGraph, GraphConfig
from watercooler_memory.leanrag_export import export_to_leanrag


def main():
    parser = argparse.ArgumentParser(
        description="Build memory graph from watercooler threads"
    )
    parser.add_argument(
        "threads_dir",
        type=Path,
        help="Path to threads directory or repo root (will look for .watercooler/)",
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Output path for graph JSON",
    )
    parser.add_argument(
        "--export-leanrag",
        type=Path,
        help="Export to LeanRAG format at this directory",
    )
    parser.add_argument(
        "--branch",
        help="Git branch context",
    )
    args = parser.parse_args()

    # Resolve threads directory
    threads_dir = args.threads_dir
    if not threads_dir.exists():
        print(f"Error: Path not found: {threads_dir}", file=sys.stderr)
        sys.exit(1)

    # Check for .watercooler subdirectory
    if (threads_dir / ".watercooler").is_dir():
        threads_dir = threads_dir / ".watercooler"
    elif not any(threads_dir.glob("*.md")):
        print(f"Error: No .md files found in {threads_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Threads directory: {threads_dir}")

    # Configure
    config = GraphConfig()

    # Progress callback
    def progress(current, total, message):
        if total > 0:
            print(f"   {message} ({current}/{total})", flush=True)
        else:
            print(f"   {message}", flush=True)

    # Build graph
    print("Building memory graph...")
    graph = MemoryGraph(config)

    try:
        graph.build(threads_dir, branch_context=args.branch, progress_callback=progress)
    except Exception as e:
        print(f"Error: Build failed: {e}", file=sys.stderr)
        sys.exit(1)

    # Stats
    stats = graph.stats()
    print(f"Built graph:")
    print(f"   Threads:  {stats['threads']}")
    print(f"   Entries:  {stats['entries']}")
    print(f"   Chunks:   {stats['chunks']}")
    print(f"   Edges:    {stats['edges']}")

    # Save graph JSON
    if args.output:
        graph.save(args.output)
        print(f"Saved graph: {args.output}")

    # Export to LeanRAG
    if args.export_leanrag:
        manifest = export_to_leanrag(
            graph,
            args.export_leanrag,
            include_embeddings=False,  # Embeddings generated by LeanRAG pipeline
        )
        print(f"Exported LeanRAG format: {args.export_leanrag}")
        print(f"   Documents: {manifest['statistics']['documents']}")
        print(f"   Chunks: {manifest['statistics']['chunks']}")
        print()
        print("Next steps:")
        print("   1. Run LeanRAG entity extraction on the exported data")
        print("   2. See ../LeanRAG/SETUP.md for the full pipeline")


if __name__ == "__main__":
    main()
